spring.application.name=exam-api
# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/${EXAMAPI_POSTGRES_DBNAME:exam_db}
spring.datasource.username=${EXAMAPI_POSTGRES_ADMIN}
spring.datasource.password=${EXAMAPI_POSTGRES_PASSWORD}


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

app.admin.username=${EXAMAPI_DEFAULT_ADMIN}
app.admin.password=${EXAMAPI_DEFAULT_PASSWORD}
app.key=${EXAMAPI_APP_KEY}