spring.application.name=exam-api
# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/${EXAMAPI_POSTGRES_DBNAME:exam_db}
spring.datasource.username=${EXAMAPI_POSTGRES_ADMIN}
spring.datasource.password=${EXAMAPI_POSTGRES_PASSWORD}

# JPA / Hibernate Settings
# "update" creates tables automatically based on your Entity classes
spring.jpa.hibernate.ddl-auto=update
# Show SQL in logs so you can see what Spring generates (Great for learning)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true