spring.application.name=exam-api
# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/${EXAMAPI_POSTGRES_DBNAME:exam_db}
spring.datasource.username=${EXAMAPI_POSTGRES_ADMIN}
spring.datasource.password=${EXAMAPI_POSTGRES_PASSWORD}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.web=DEBUG

app.admin.username=admin
app.admin.password=password